### PR TITLE
Add virtual fish to prompt

### PR DESCRIPTION
**Pull request by talha131**
Virtual Fish[1] is a wrapper for Ian Bicking's virtualenv. This commit
shows the currently active virtual environment in the prompt.

[1]: https://github.com/adambrenecki/virtualfish/

### CODE REVIEW

**Comment by bpinto** [comment]
Ping @tannhuber

**Comment by tannhuber** [comment]
@talha131 :+1: Thank you!

Unfortunately, I'm not familiar with python development. It would be nice to have a comment in the README as well.

**Comment by talha131** [comment]
@tannhuber I have updated Readme.

**Comment by tannhuber** [comment]
From my point of view: OK

**Comment by tannhuber** [comment]
Ping @bpinto: Do you want to merge the two pending pull requests for budspencer theme? Or is there anything else to do?

**Comment by bpinto** [comment]
@tannhuber they look good to me. 

P.s.: You have your admin rights again - they were removed by bucaran. :(

**Comment by tannhuber** [comment]
Thank you!

**Pull request merged**
