### PR TITLE
Move files to be compatible with Fisher standards

### PR DESCRIPTION
**Pull request by g00ntar**
Fisher drops *.fish files outside functions folder.

### CODE REVIEW

**Comment by ngmoviedo** [comment]
You may need to do something about the README too, as it is shown when calling `budspencer_help`. I think I might have solved that too in my PR #76.
I ended up solving a couple of issues I had with this theme too, although I'm not sure how general they were.
I guess that maintaining compatibility with OMF and Fisher at the same time might be out of the scope of this project. But I'll try to maintain my Fisher-compatible fork, as I really like this prompt.
Maybe you can check it out, to check if it works alright.

**Review by scorphus — APPROVED** [review]
Thanks, @g00ntar.

From what I can tell, there's no need to change nor move README.md.

I tested on few different Fish 3.[1,2].x versions (using docker containers) with both Ubuntu and Debian. Nevertheless I thought I'd give other maintainers a chance to review it too.

**Comment by ngmoviedo** [comment]
It is necessary to move the README.md file, as it is shown when you execute budspencer_help. If it was installed with fisher, you'll get the following error:

> /themes/budspencer/README.md wasn't found.

First, that directory won't even exist if you're using fisher, and the README.md doesn't even get downloaded by fisher. This can be solved by moving the README to the functions directory and modifying the code so it points to the right directory when calling budspencer_help.

**Comment by scorphus** [comment]
Got it, @ngmoviedo. Can you please confirm if it works on Fisher after the last change? Thanks in advance.

p.s.: we can solve #75 with another PR (or in even in #76)

**Comment by ngmoviedo** [comment]
The README.md get downloaded by fisher now, but it's still not displayed when executing `budspencer_help`. This happens because the function, defined in `fish_prompt.fish` looks for the readme in `$OMF_PATH/themes/budspencer/README.md`, so it is able to locate it only for OMF users. 
Here are the [relevant lines](https://github.com/g00ntar/theme-budspencer/blob/9faa558734f6ee82d5dc6aa38cc73bb1e6d9c362/functions/fish_prompt.fish#L86-L101).
I think something like [this](https://github.com/ngmoviedo/theme-budspencer/blob/28d6f009c9b226a2b4105f67a7acaf67508094c4/functions/fish_prompt.fish#L86-L107) would solve the issue.
Sorry for the links, I'm not sure how to comment the code on the PR fir a the file that was only moved without changes.

P.S.: I don't know exactly what changed, but I can't reproduce #75 anymore. I'll close that issue and #76.

**Review by ngmoviedo — CHANGES_REQUESTED** [review]
For the README to get displayed when calling `budspencer_help`, a change is required in [these lines](https://github.com/g00ntar/theme-budspencer/blob/9faa558734f6ee82d5dc6aa38cc73bb1e6d9c362/functions/fish_prompt.fish#L86-L101) too.
I think that would be the only detail left for a full compatibility with Fisher.

**Comment by ngmoviedo** [comment]
> Here are the [relevant lines](https://github.com/g00ntar/theme-budspencer/blob/9faa558734f6ee82d5dc6aa38cc73bb1e6d9c362/functions/fish_prompt.fish#L86-L101).
> I think something like [this](https://github.com/ngmoviedo/theme-budspencer/blob/28d6f009c9b226a2b4105f67a7acaf67508094c4/functions/fish_prompt.fish#L86-L107) would solve the issue.

Sorry, I forgot about the last link when I deleted the fork. I'll rewrite it as soon as I can.

**Comment by ngmoviedo** [comment]
Updated the PR. Noticed that it is not enough for the `readme_file` variable to be set locally with `set -l`. It needs to be exported with `set -x`.

**Comment by scorphus** [comment]
I thought of a way to solve the README.md problem. But I think that is a subject for another PR. Let's get this one merged first 🙂

**Comment by scorphus** [comment]
So, without considering `budspencer_help`, can you please confirm this works on Fisher, @ngmoviedo? Thanks.

**Comment by ngmoviedo** [comment]
Yes, I haven't noticed any other problem at all.

**Review by ngmoviedo — APPROVED** [review]

**Comment by scorphus** [comment]
Thank you, @ngmoviedo! 🙌

**Pull request merged**
